application: eansresume
version: v1
threadsafe: true

runtime: go
api_version: go1

handlers:
- url: /_ah/api/.*
  script: _go_app
  
- url: /_ah/spi/.*
  script: _go_app

- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /
  static_dir: html
  
builtins:
- remote_api: on